module.exports = correo = () => {
    var emailHtml = '<!doctype html>';
    emailHtml += '<html>';
    emailHtml += ' <head>';
    emailHtml += '<meta name="viewport" content="width=device-width" />';
    emailHtml += '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />';
    emailHtml += '<title>Simple Transactional Email</title>';
    emailHtml += '<style>';
    emailHtml += 'img {';
    emailHtml += 'border: none;';
    emailHtml += '-ms-interpolation-mode: bicubic;';
    emailHtml += 'max-width: 100%; ';
    emailHtml += '}';
    emailHtml += 'body {';
    emailHtml += 'background-color: #f6f6f6;';
    emailHtml += 'font-family: sans-serif;';
    emailHtml += '-webkit-font-smoothing: antialiased;';
    emailHtml += 'font-size: 14px;';
    emailHtml += 'line-height: 1.4;';
    emailHtml += 'margin: 0;';
    emailHtml += 'padding: 0;';
    emailHtml += '-ms-text-size-adjust: 100%;';
    emailHtml += '-webkit-text-size-adjust: 100%; ';
    emailHtml += '}';
    emailHtml += ' table {';
    emailHtml += 'border-collapse: separate;';
    emailHtml += 'mso-table-lspace: 0pt;';
    emailHtml += 'mso-table-rspace: 0pt;';
    emailHtml += 'width: 100%; }';
    emailHtml += 'table td {';
    emailHtml += 'font-family: sans-serif;';
    emailHtml += 'font-size: 14px;';
    emailHtml += 'vertical-align: top; ';
    emailHtml += '}';
    emailHtml += '.body {';
    emailHtml += 'background-color: #f6f6f6;';
    emailHtml += 'width: 100%; ';
    emailHtml += '}';
    emailHtml += '.container {';
    emailHtml += 'display: block;';
    emailHtml += 'margin: 0 auto !important;';
    emailHtml += ' max-width: 580px;';
    emailHtml += 'padding: 10px;';
    emailHtml += 'width: 580px; ';
    emailHtml += '}';
    emailHtml += '.content {';
    emailHtml += 'box-sizing: border-box;';
    emailHtml += 'display: block;';
    emailHtml += 'margin: 0 auto;';
    emailHtml += ' max-width: 580px;';
    emailHtml += 'padding: 10px; ';
    emailHtml += '}';
    emailHtml += '.main {';
    emailHtml += 'background: #ffffff;';
    emailHtml += ' border-radius: 3px;';
    emailHtml += 'width: 100%; ';
    emailHtml += '}';
    emailHtml += '.wrapper {';
    emailHtml += 'box-sizing: border-box;';
    emailHtml += 'padding: 20px; ';
    emailHtml += '}';
    emailHtml += '.content-block {';
    emailHtml += 'padding-bottom: 10px;';
    emailHtml += 'padding-top: 10px;';
    emailHtml += '}';
    emailHtml += '.footer {';
    emailHtml += 'clear: both;';
    emailHtml += 'margin-top: 10px;';
    emailHtml += 'text-align: center;';
    emailHtml += 'width: 100%; ';
    emailHtml += '}';
    emailHtml += '.footer td,';
    emailHtml += '.footer p,';
    emailHtml += '.footer span,';
    emailHtml += '.footer a {';
    emailHtml += 'color: #999999;';
    emailHtml += ' font-size: 12px;';
    emailHtml += 'text-align: center; ';
    emailHtml += '}';
    emailHtml += 'h1,';
    emailHtml += 'h2,';
    emailHtml += 'h3,';
    emailHtml += 'h4 {';
    emailHtml += 'color: #000000;';
    emailHtml += 'font-family: sans-serif;';
    emailHtml += 'font-weight: 400;';
    emailHtml += 'line-height: 1.4;';
    emailHtml += 'margin: 0;';
    emailHtml += 'margin-bottom: 30px; ';
    emailHtml += '}';
    emailHtml += 'h1 {';
    emailHtml += 'font-size: 35px;';
    emailHtml += 'font-weight: 300;';
    emailHtml += 'text-align: center;';
    emailHtml += 'text-transform: capitalize; ';
    emailHtml += '}';
    emailHtml += 'p,';
    emailHtml += 'ul,';
    emailHtml += 'ol {';
    emailHtml += 'font-family: sans-serif;';
    emailHtml += 'font-size: 14px;';
    emailHtml += 'font-weight: normal;';
    emailHtml += 'margin: 0;';
    emailHtml += 'margin-bottom: 15px; ';
    emailHtml += '}';
    emailHtml += 'p li,ul li,ol li {';
    emailHtml += 'list-style-position: inside;';
    emailHtml += 'margin-left: 5px; ';
    emailHtml += '}';
    emailHtml += 'a {';
    emailHtml += 'color: #3498db;';
    emailHtml += 'text-decoration: underline; ';
    emailHtml += '}';
    emailHtml += '.btn {';
    emailHtml += 'box-sizing: border-box;';
    emailHtml += 'width: 100%; }';
    emailHtml += '.btn > tbody > tr > td {';
    emailHtml += 'padding-bottom: 15px; }';
    emailHtml += '.btn table {';
    emailHtml += 'width: auto; ';
    emailHtml += '}';
    emailHtml += '.btn table td {';
    emailHtml += 'background-color: #ffffff;';
    emailHtml += 'border-radius: 5px;';
    emailHtml += 'text-align: center; ';
    emailHtml += '}';
    emailHtml += '.btn a {';
    emailHtml += 'background-color: #ffffff;';
    emailHtml += 'border: solid 1px #3498db;';
    emailHtml += 'border-radius: 5px;';
    emailHtml += 'box-sizing: border-box;';
    emailHtml += 'color: #3498db;';
    emailHtml += 'cursor: pointer;';
    emailHtml += 'display: inline-block;';
    emailHtml += 'font-size: 14px;';
    emailHtml += 'font-weight: bold;';
    emailHtml += 'margin: 0;';
    emailHtml += 'padding: 12px 25px;';
    emailHtml += 'text-decoration: none;';
    emailHtml += 'text-transform: capitalize; ';
    emailHtml += '}';
    emailHtml += '.btn-primary table td {';
    emailHtml += 'background-color: #3498db; ';
    emailHtml += '}';
    emailHtml += '.btn-primary a {';
    emailHtml += 'background-color: #3498db;';
    emailHtml += 'border-color: #3498db;';
    emailHtml += 'color: #ffffff; ';
    emailHtml += '}';
    emailHtml += '.last {';
    emailHtml += 'margin-bottom: 0; ';
    emailHtml += '}';
    emailHtml += '.first {';
    emailHtml += 'margin-top: 0; ';
    emailHtml += '}';
    emailHtml += '.align-center { text-align: center;  }';
    emailHtml += '.align-right {text-align: right; }';
    emailHtml += '.align-left {text-align: left; }';
    emailHtml += ' .clear {clear: both; }';
    emailHtml += '.mt0 {margin-top: 0; }';
    emailHtml += '.mb0 { margin-bottom: 0; }';
    emailHtml += '.preheader {';
    emailHtml += 'color: transparent;';
    emailHtml += 'display: none;';
    emailHtml += 'height: 0;';
    emailHtml += 'max-height: 0;';
    emailHtml += 'max-width: 0;';
    emailHtml += 'opacity: 0;';
    emailHtml += 'overflow: hidden;';
    emailHtml += 'mso-hide: all;';
    emailHtml += 'visibility: hidden;';
    emailHtml += 'width: 0; ';
    emailHtml += '}';
    emailHtml += '.powered-by a { text-decoration: none; }';
    emailHtml += 'hr {';
    emailHtml += 'border: 0;';
    emailHtml += 'border-bottom: 1px solid #f6f6f6;';
    emailHtml += 'margin: 20px 0; ';
    emailHtml += '}';
    emailHtml += '@media only screen and (max-width: 620px) {';
    emailHtml += 'table[class=body] h1 {';
    emailHtml += 'font-size: 28px !important;';
    emailHtml += 'margin-bottom: 10px !important; ';
    emailHtml += '}';
    emailHtml += 'table[class=body] p,';
    emailHtml += 'table[class=body] ul,';
    emailHtml += 'table[class=body] ol,';
    emailHtml += 'table[class=body] td,';
    emailHtml += 'table[class=body] span,';
    emailHtml += 'table[class=body] a {';
    emailHtml += 'font-size: 16px !important; ';
    emailHtml += '}';
    emailHtml += 'table[class=body] .wrapper,';
    emailHtml += 'table[class=body] .article {';
    emailHtml += 'padding: 10px !important; ';
    emailHtml += '}';
    emailHtml += 'table[class=body] .content {';
    emailHtml += 'padding: 0 !important; ';
    emailHtml += '}';
    emailHtml += 'table[class=body] .container {';
    emailHtml += 'padding: 0 !important;';
    emailHtml += 'width: 100% !important; ';
    emailHtml += '}';
    emailHtml += 'table[class=body] .main {';
    emailHtml += 'border-left-width: 0 !important;';
    emailHtml += 'border-radius: 0 !important;';
    emailHtml += 'border-right-width: 0 !important; ';
    emailHtml += '}';
    emailHtml += 'table[class=body] .btn table {';
    emailHtml += 'width: 100% !important; ';
    emailHtml += '}';
    emailHtml += 'table[class=body] .btn a {';
    emailHtml += 'width: 100% !important; ';
    emailHtml += '}';
    emailHtml += 'table[class=body] .img-responsive {';
    emailHtml += 'height: auto !important;';
    emailHtml += 'max-width: 100% !important;';
    emailHtml += 'width: auto !important; ';
    emailHtml += '}';
    emailHtml += '}';
    emailHtml += '@media all {';
    emailHtml += '.ExternalClass {width: 100%; }';
    emailHtml += '.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {';
    emailHtml += 'line-height: 100%; ';
    emailHtml += '}';
    emailHtml += '.apple-link a {';
    emailHtml += 'color: inherit !important;';
    emailHtml += 'font-family: inherit !important;';
    emailHtml += 'font-size: inherit !important;';
    emailHtml += 'font-weight: inherit !important;';
    emailHtml += 'line-height: inherit !important;';
    emailHtml += 'text-decoration: none !important; ';
    emailHtml += '}';
    emailHtml += '#MessageViewBody a {';
    emailHtml += 'color: inherit;';
    emailHtml += 'text-decoration: none;';
    emailHtml += 'font-size: inherit;';
    emailHtml += 'font-family: inherit;';
    emailHtml += 'font-weight: inherit;';
    emailHtml += 'line-height: inherit;';
    emailHtml += '}';
    emailHtml += '.btn-primary table td:hover {';
    emailHtml += 'background-color: #34495e !important; ';
    emailHtml += '}';
    emailHtml += '.btn-primary a:hover {';
    emailHtml += 'background-color: #34495e !important;';
    emailHtml += 'border-color: #34495e !important; ';
    emailHtml += '} ';
    emailHtml += '}';
    emailHtml += '</style>';
    emailHtml += '</head>';
    emailHtml += '<body class="">';
    emailHtml += '<span class="preheader">This is preheader text. Some clients will show this text as a preview.</span>';
    emailHtml += '<table role="presentation" border="0" cellpadding="0" cellspacing="0" class="body">';
    emailHtml += '<tr>';
    emailHtml += '<td>&nbsp;</td>';
    emailHtml += '<td class="container">';
    emailHtml += '<div class="content">';
    emailHtml += '<table role="presentation" class="main">';
    emailHtml += ' <tr>';
    emailHtml += '<td class="wrapper">';
    emailHtml += '<table role="presentation" border="0" cellpadding="0" cellspacing="0">';
    emailHtml += '<tr>';
    emailHtml += '<td>';
    emailHtml += '<p>Hi there,</p>';
    emailHtml += '<p>Sometimes you just want to send a simple HTML email with a simple design and clear call to action. This is it.</p>';
    emailHtml += '<table role="presentation" border="0" cellpadding="0" cellspacing="0" class="btn btn-primary">';
    emailHtml += '<tbody>';
    emailHtml += '<tr>';
    emailHtml += '<td align="left">';
    emailHtml += '<table role="presentation" border="0" cellpadding="0" cellspacing="0">';
    emailHtml += '<tbody>';
    emailHtml += '<tr>';
    emailHtml += '<td> <a href="http://htmlemail.io" target="_blank">Call To Action</a> </td>';
    emailHtml += ' </tr>';
    emailHtml += '</tbody>';
    emailHtml += '</table>';
    emailHtml += '</td>';
    emailHtml += '</tr>';
    emailHtml += '</tbody>';
    emailHtml += '</table>';
    emailHtml += '<p>This is a really simple email template. Its sole purpose is to get the recipient to click the button with no distractions.</p>';
    emailHtml += '<p>Good luck! Hope it works.</p>';
    emailHtml += '</td>';
    emailHtml += '</tr>';
    emailHtml += '</table>';
    emailHtml += '</td>';
    emailHtml += '</tr>';
    emailHtml += '<!-- END MAIN CONTENT AREA -->';
    emailHtml += '</table>';
    emailHtml += '<!-- END CENTERED WHITE CONTAINER -->';
    emailHtml += '<div class="footer">';
    emailHtml += '<table role="presentation" border="0" cellpadding="0" cellspacing="0">';
    emailHtml += '<tr>';
    emailHtml += '<td class="content-block">';
    emailHtml += '<span class="apple-link">Company Inc, 3 Abbey Road, San Francisco CA 94102</span>';
    emailHtml += '<br> Dont like these emails? <a href="http://i.imgur.com/CScmqnj.gif">Unsubscribe</a>.';
    emailHtml += '</td>';
    emailHtml += '</tr>';
    emailHtml += '<tr>';
    emailHtml += '<td class="content-block powered-by">';
    emailHtml += 'Powered by <a href="http://htmlemail.io">HTMLemail</a>.';
    emailHtml += '</td>';
    emailHtml += '</tr>';
    emailHtml += '</table>';
    emailHtml += '</div>';
    emailHtml += '</div>';
    emailHtml += '</td>';
    emailHtml += '<td>&nbsp;</td>';
    emailHtml += '</tr>';
    emailHtml += '</table>';
    emailHtml += '</body>';
    emailHtml += '</html>';
    return emailHtml;
}