const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ScoreDps = mongoose.model('dps', new Schema({
    NumeroDocumento:String,
    idCogestor: String,
    TotalScore:String,
    CasosScore:[
        {
            Caso:String,
            Repetition:[{
                    idProgramacionHogar:String,
                    idHogar: String,
                    hogarModificado: String,
                    IMEI: String,
                    FechaServidor: String,
                    FechaInicioSesion: String,
                    FechaFinalSesion: String,
                    FuenteFallo: String,
                    Integrantes: [{
                        IdHogar: String,
                        IdTipoDocumento: String,
                        NumeroDocumento: String,
                        NombreCompleto: String,
                        FechaNacimiento: String,
                        FechaExpedicionDocumento: String,
                        PrimerNombre: String,
                        SegundoNombre: String,
                        PrimerApellido: String,
                        SegundoApellido: String,
                        IdIntegranteHogar: String,
                        IdGenero: String,
                        IdEstadoIntegrante: String,
                        TieneLibretaMilitar: String,
                        EsJefeHogar: String,
                        FechaRegistro: String,
                        FechaActualizacion: String,
                        EdadCaracterizacion: String,
                        TieneDocumentoIdentidad: String,
                        Orden: String,
                        E03A: String,
                        E03B: String,
                        E031: String,
                        IdDepartamento: String,
                        IdMunicipio: String,
                        IdPaisNacionalidad: String,
                        EsConLector: String,
                        esNuevo: String,
                        esModificado: String
                    }
                    ],
                    HogaresConIntegrantes: String,
                    Coordenadas: [{
                        idCoordenadaSesion: String,
                        idHogar: String,
                        sesion: String,
                        momento: String,
                        fechaGeoPunto: String,
                        longitud: String,
                        latitud: String,
                        altitud: String
                    }
                    ],
                    Hogar: {
                    idHogar: String,
                    idHogarFocalizacion: String,
                    idModelo: String,
                    ordenPriorizacion: String,
                    acuerdoInformacion: String,
                    fechaRegistro: String,
                    fechaRegistroFocalizacion: String,
                    idEstadoHogar: String,
                    idFuente:String,
                    Fechainactivacion: String
                    },
                    Encuesta: {
                    idProgramacionHogar: String,
                    fechaInicio: String,
                    idEstado: String,
                    medioDiligenciamiento: String,
                    informador: String,
                    idResponsable: String,
                    idHogar: String,
                    AcuerdoInformacion: String,
                    fotoAcuerdoInformacion: String,
                    fotoRenunciaVoluntaria: String,
                    estado: String,
                    fotoSoporteEncuesta: String
                    },
                    UbicacionHogar: {
                    idHogar: String,
                    IdRegion: String,
                    IdDepartamento: String,
                    IdMunicipio: String,
                    IdZona: String,
                    IdLocalidadComuna: String,
                    IdCentroPoblado: String,
                    OtroCentroPoblado: String,
                    Direccion: String,
                    IdBarrio: String,
                    OtroBarrio: String,
                    IdCorregimiento: String,
                    OtroCorregimiento: String,
                    IdVereda: String,
                    OtroVereda: String,
                    Longitud: String,
                    Latitud: String,
                    Altitud: String,
                    fotoFachada: String
                    },
                    ContactoHogar: {
                    idHogar: String,
                    idProgramacionHogar: String,
                    TelefonoFijo: String,
                    TelefonoCelular1: String,
                    TelefonoCelular2: String,
                    CorreoElectronic: String
                    },
                    CapituloB: {
                    IdHogar: String,
                    idEncuesta: String,
                    B01: String,
                    B02: String,
                    B03: String,
                    B04: String,
                    B06E: String,
                    B05: String,
                    B01_1: String,
                    B02_1: String,
                    B03_1: String,
                    B05_1: String,
                    B06: String,
                    B06A: String,
                    B07: String,
                    B08: String,
                    B08_1: String,
                    B06_1A: String,
                    B06_5A: String,
                    B06_5B: String,
                    B08_A: String
                    },
                    CapituloC: {
                    IdHogar: String,
                    idEncuesta: String,
                    C01: String,
                    C02: String,
                    C03: String,
                    C04: String,
                    C05: String,
                    C05_1: String,
                    C05_2: String,
                    C06: String,
                    C07: String,
                    C08: String,
                    C08_1: String,
                    C09: String,
                    C09_1: String,
                    C10: String,
                    C10_1: String,
                    C11: String,
                    C11_1: String,
                    C12: String,
                    C13: String,
                    C13_1: String,
                    C14: String,
                    C15: String,
                    C16: String,
                    C17: String,
                    C18: String,
                    C18_1: String,
                    C19: String,
                    C20: String,
                    C21: String,
                    C22: String,
                    C53: String,
                    C55: String,
                    C56: String,
                    C08_A: String,
                    C17_A: String,
                    C19_A: String
                    },
                    CapituloD:
                    {
                        IdHogar:String,
                        idEncuesta:String,
                        D01:String,
                        D02:String,
                        D03:String,
                        D04:String,
                        D04_1:String,
                        D03_1:String,
                        D03_2:String
                    },
                    IntegrantesHogar:String,
                    ListaCapituloE:[{
                        IdHogar:String,
                        IdIntegranteHogar:String,
                        idCapituloE:String,
                        idEncuesta:String,
                        E04:String,
                        E05:String,
                        E06:String,
                        E06_1:String,
                        E10:String,
                        E11_1:String,
                        E11_2:String,
                        E12:String,
                        E13:String,
                        E14:String,
                        E15:String,
                        E16:String,
                        E16_1:String,
                        E17:String,
                        E17_1:String,
                        E18:String,
                        fechaRegistro:String,
                        idEstado:String,
                        idResponsable:String
                    }],
                    ListaCapituloF:[{
                        IdHogar:String,
                        IdIntegranteHogar:String,
                        idCapituloE:String,
                        idEncuesta:String,
                        F01:String,
                        F02:String,
                        F03:String,
                        F04:String,
                        F05:String,
                        F06:String,
                        F07:String,
                        F08:String,
                        F09:String,
                        F10:String,
                        F11:String,
                        F12:String,
                        F13:String,
                        F14:String,
                        F15:String,
                        F16:String,
                        F17:String,
                        F18:String,
                        F19:String,
                        F20:String,
                        F21:String,
                        F22:String,
                        F23:String,
                        fechaRegistro:String,
                        idEstado:String,
                        idResponsable:String
                    }],
                    ListaCapituloG:[],
                    ListaCapituloH:[{
                        IdHogar:String,
                        IdIntegranteHogar:String,
                        idEncuesta:String,
                        H01:String,
                        H02:String,
                        H02_A:String,
                        H03:String,
                        H04:String,
                        H04_1:String,
                        H04_1Otra:String,
                        H04_A:String,
                        H05:String,
                        H05_Otra:String,
                        H05_1:String,
                        H05_1A:String,
                        H06:String,
                        FechaRegistro:String,
                        idEstado:String,
                        idResponsable:String
                    }],
                    ListaCapituloI:[{
                        IdHogar:String,
                        IdIntegranteHogar:String,
                        idEncuesta:String,
                        I01:String,
                        I02:String,
                        I03:String,
                        I04:String,
                        I04_1:String,
                        fechaRegistro:String,
                        idEstado:String,
                        idResponsable:0
                    }],
                    ListaCapituloJ:[{
                        IdHogar:String,
                        IdIntegranteHogar:String,
                        idEncuesta:String,
                        J01:String,
                        J02:String,
                        J03:String,
                        J04:String,
                        J04_1:String,
                        J04_2:String,
                        J05:String,
                        J05_1:String,
                        J06:String,
                        J06_1:String,
                        J07:String,
                        J07_1:String,
                        J08:String,
                        J08_1:String,
                        J09_1:String,
                        J09_1A:String,
                        J09_1B:String,
                        J09_2:String,
                        J09_2A:String,
                        J09_2B:String,
                        J09_3:String,
                        J09_3A:String,
                        J09_3B:String,
                        J09_4:String,
                        J09_4A:String,
                        J09_4B:String,
                        J10_1:String,
                        J10_1A:String,
                        J10_1B:String,
                        J10_2:String,
                        J10_2A:String,
                        J10_2B:String,
                        J11_1:String,
                        J11_1A:String,
                        J11_2:String,
                        J11_2A:String,
                        J11_3:String,
                        J11_3A:String,
                        J11_4:String,
                        J11_4A:String,
                        J11_5:String,
                        J11_5A:String,
                        J12:String,
                        J13:String,
                        J13_1:String,
                        J14:String,
                        J15:String,
                        fechaRegistro:String,
                        idEstado:String,
                        idResponsable:String
                    }],
                    ListaCapituloK:[{
                        IdHogar:String,
                        IdIntegranteHogar:String,
                        idEncuesta:String,
                        K01:String,
                        K01_Otro:String,
                        K02:String,
                        K03:String,
                        K04:String,
                        K05:String,
                        K05_Otro:String,
                        K06:String,
                        K06_Otros:String,
                        K07:String,
                        K08:String,
                        K08_Otro:String,
                        K09:String,
                        K09_Otro:String,
                        K10:String,
                        K11:String,
                        K12:String,
                        K13:String,
                        K13_1A:String,
                        K13_2A:String,
                        K13_3A:String,
                        K13_4A:String,
                        K13_5A:String,
                        K13_Otro:String,
                        K13_6A:String,
                        K14:String,
                        K14_Otro:String,
                        K15:String,
                        K15_Otro:String,
                        K16:String,
                        K17:String,
                        K17_Otro:String,
                        K18:String,
                        K19:String,
                        K20:String,
                        K21:String,
                        K21_Otro:String,
                        K22:String,
                        K22_Otro:String,
                        K23:String,
                        K23_Otro:String,
                        K24:String,
                        K24_1A:String,
                        K24_2A:String,
                        K24_3A:String,
                        K24_4A:String,
                        K24_5A:String,
                        K24_Otro:String,
                        K24_6A:String,
                        K25:String,
                        K25_Otro:String,
                        K26:String,
                        K26_Otro:String,
                        K27:String,
                        FechaRegistro:String,
                        EstadoIntegranteCapitulo:String,
                        idEstado:String,
                        idResponsable:String
                    }],
                    ListaCapituloL:[{
                        IdHogar:String,
                        IdIntegranteHogar:String,
                        idCapituloL:String,
                        idEncuesta:String,
                        finalizacionEncuesta:String,
                        L01:String,
                        L02_1:String,
                        L02_1A:String,
                        L02_2:String,
                        L02_2A:String,
                        L02_3:String,
                        L02_3A:String,
                        L03:String,
                        L04_1:String,
                        L04_1A:String,
                        L04_2:String,
                        L04_2A:String,
                        L04_3:String,
                        L04_3A:String,
                        L04_4:String,
                        L04_4A:String,
                        L04_5:String,
                        L04_5A:String,
                        L04_6:String,
                        L04_6A:String,
                        L05_1:String,
                        L05_1A:String,
                        L05_2:String,
                        L05_2A:String,
                        L05_3:String,
                        L05_4:String,
                        L05_5:String,
                        fechaRegistro:String,
                        idEstado:String,
                        idResponsable:String
                    }],
                    ListaOferta:String,
                    MensajeError:String
                }
            ]
            
        }
    ],
}));

module.exports = ScoreDps;